### ISSUE TITLE
Fazer Interface

### ISSUE THREAD

**Issue by MRLimcon** [MRLimcon/Adblock#6]

**Comment by HenriqueHida** [comment]
Semana 5 trabalho DDS

**Comment by pedrobarbosaocb** [comment]
Eu vou fazer com o Hidão essa

**Comment by MRLimcon** [comment]
Adicionar as opções:
- Ativação e desativação de bloqueio de cosméticos, bloqueio de domínios e bloqueio de cookies;
- Algo para adicionar listas de bloqueios.
- Bloquear ou desbloquear algum domínio do site.
