### ISSUE TITLE
Linkar backend e popup - Henrique

### ISSUE THREAD

**Issue by MRLimcon** [MRLimcon/Adblock#9]
Fazer os scripts rodarem com as ações no popup:
- Ativar e desativar os bloqueios de cosméticos, cookies e domínios;
- Linkar a função de adicionar listas e excluir listas com a opção do popup;
- Linkar a função de bloquear ou dar whitelist em um domínio pelo usuário.

**Comment by HenriqueHida** [comment]
Deixa comigo
